import java.sql.*;
import javax.swing.JOptionPane;
import javaapplication4.JavaApplication4; 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("USERNAME");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("PASSWORD");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        submit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        submit.setText("LOGIN");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("NEW REGISTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jPasswordField1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(submit)
                        .addGap(85, 85, 85)
                        .addComponent(jButton2)
                        .addContainerGap(112, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(jButton2))
                .addGap(45, 45, 45))
        );

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Online Movie Ticket Booking");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // new movie().setVisible(true); 
       //  String s1;
                 //s1=evt.getActionCommand();
         workWithDatabase();
    }
//    public void workWithDatabase()
//    {
//         Connection c=null;
//         Statement  s=null;
//         ResultSet rs=null;
//         int flag=0;
//    
//         //if(s1.equals("submit"))
//   {
//   try
//   {
////       Class.forName("com.mysql.cj.jdbc.Driver");
////       c=DriverManager.getConnection("jdbc:mysql://localhost/java_dbmovies","root","25082003");
//       c=JavaApplication4.ConnecrDb();
//       s=c.createStatement();
//       String a=jTextField1.getText();
//       String b=jPasswordField1.getText();
//       rs=s.executeQuery("select name,password from register");
//       while(rs.next())
//       {       //flag=1;
//               String ename=rs.getString("name");
//               String pass=rs.getString("password");
//        if(a.equals(ename) && b.equals(pass))
//        {  
//           
//        JOptionPane.showMessageDialog(this,"Logined successfully");
//       this.setVisible(false);   new movie().setVisible(true);
//         //continue;
//         break;
//         }
//       /** else
//        {
//            // System.out.println("enter valid details");
//           //JOptionPane.showMessageDialog(null,"Invalid password or Username");
//            //break;
//         
//        }**/
//       
//       
//        else if("".equals(a) && "".equals(b))
//       {
//           JOptionPane.showMessageDialog(this,"please enter valid details");
//           break;
//           
//       }
//       }
//       /**if(flag==0)
//        {
//           setVisible(true);
//        }**/
//       }
//       
//   catch(Exception e)
//     {
//          System.out.println(e);
//      }
//   }
//       
//   
//    
//   // TODO add your handling code here:
public void workWithDatabase() {
    Connection c = null;
    PreparedStatement pst = null; // **قم بتعريف PreparedStatement هنا**
    ResultSet rs = null;
    int loggedInUserId = -1; // **متغير جديد لتخزين معرف المستخدم الذي قام بتسجيل الدخول**

    // احصل على اسم المستخدم وكلمة المرور من حقول النص
    String username = jTextField1.getText().trim(); // استخدم .trim() لإزالة المسافات البيضاء
    String password = jPasswordField1.getText().trim();

    // تحقق من أن الحقول ليست فارغة قبل المتابعة
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter both username and password.");
        return;
    }

    try {
        // الحصول على اتصال بقاعدة البيانات
        c = JavaApplication4.ConnecrDb();
        if (c == null) {
            JOptionPane.showMessageDialog(this, "Database connection not established. Please check connection settings.");
            return;
        }

        // **1. تعريف الاستعلام مع جلب ID:**
        // هذا هو الاستعلام الذي يجلب ID، الاسم، وكلمة المرور للمستخدمين الذين يتطابقون
        String sql = "SELECT id, name, password FROM register WHERE name = ? AND password = ?";
        
        // **2. إعداد PreparedStatement:**
        // استخدام PreparedStatement بدلاً من Statement العادي للأمان والكفاءة
        pst = c.prepareStatement(sql);
        
        // **3. تعيين القيم لعلامات الاستفهام (`?`):**
        // يتم تعيين القيمة الأولى لعلامة الاستفهام الأولى (name)
        pst.setString(1, username);
        // يتم تعيين القيمة الثانية لعلامة الاستفهام الثانية (password)
        pst.setString(2, password);

        // **4. تنفيذ الاستعلام:**
        // تنفيذ الاستعلام والحصول على النتائج في ResultSet
        rs = pst.executeQuery();

        // **5. معالجة النتائج وجلب ID:**
        // rs.next() تُعيد true إذا كان هناك سجل (صف) واحد على الأقل يطابق الاستعلام
        if (rs.next()) {
            loggedInUserId = rs.getInt("id"); // **جلب قيمة ID من عمود 'id'**
            JOptionPane.showMessageDialog(this, "Logged in successfully!");
            this.setVisible(false); // إخفاء نافذة تسجيل الدخول

            // **6. تمرير ID إلى شاشة الحجز (`movie`):**
            // إنشاء كائن جديد من كلاس movie وتمرير معرف المستخدم إليه
            // (تتطلب هذه الخطوة وجود مُنشئ في كلاس movie يستقبل int)
            new movie(loggedInUserId).setVisible(true);

        } else {
            // إذا لم يتم العثور على أي سجل يطابق اسم المستخدم وكلمة المرور
            JOptionPane.showMessageDialog(this, "Invalid username or password.");
        }

    } catch (SQLException e) {
        // التعامل مع أي استثناءات SQL (مثل مشاكل الاتصال، أخطاء في الاستعلام، إلخ)
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        e.printStackTrace(); // طباعة تتبع الخطأ لتصحيحه في لوحة التحكم
    } finally {
        // **7. إغلاق الموارد في كتلة finally:**
        // هذا يضمن إغلاق الاتصال والموارد الأخرى حتى لو حدث خطأ.
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (c != null) c.close();
        } catch (SQLException e) {
            e.printStackTrace(); // طباعة أي أخطاء أثناء إغلاق الموارد
        }
    }

    }//GEN-LAST:event_submitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);    new register().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
