import java.sql.*;
import java.util.logging.Logger; // استيراد Logger
import javax.swing.SwingUtilities;
import javax.swing.JLabel; // لاستخدام JLabel
import javax.swing.JOptionPane; // لعرض رسائل للمستخدم
import javax.swing.SwingWorker;
import javaapplication4.JavaApplication4;// لتعدد المهام

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PRATAP KUMAR
 */
public class recepit extends javax.swing.JFrame {
private int bookingId;
    // تعريف Logger (نفس الطريقة التي استخدمتها سابقًا)
    private static final Logger logger = Logger.getLogger(recepit.class.getName());

    public recepit() {
        initComponents();
        // تهيئة statusLabel هنا أو في initComponents
       myStatusLabel = new JLabel(" "); // إضافة JLabel جديد
        jPanel1.add(myStatusLabel); // أضف الـ JLabel إلى لوحتك الرئيسية
        // يمكنك ضبط موقع وحجم statusLabel باستخدام GroupLayout أو LayoutManager آخر
        // لتبسيط المثال، سأضيفه إلى jPanel1 وسيفترض مكانه حسب LayoutManager الخاص بـ jPanel1
        // في NetBeans Designer، يمكنك سحب JLabel وتسميته statusLabel
        // وتعديل GroupLayout يدوياً أو عبر Designer لوضعه في مكان مناسب (مثلاً أسفل الأزرار)
        // لهذا المثال، سأفترض أنك أضفته في Designer أو ستضيفه يدوياً
        // For demonstration, let's assume it's placed somewhere accessible, maybe below jPanel1.
        // It's best to place it visually in NetBeans Designer.
        // For now, let's just make sure it's instantiated.
    }

    String a;String b;String c;String e;String f;
    double  N1;

    public recepit(int bookingId, String p1, String p2, String p3, String p4, double p5, String p6) {
    initComponents();
    this.bookingId = bookingId;  // مهم جداً هنا
    this.a = p1;
    this.b = p2;
    this.c = p3;
    this.e = p4;
    this.N1 = p5;
    this.f = p6;
    jLabel7.setText(p4);
    jLabel8.setText(p2);
    jLabel9.setText(p1);
    jLabel10.setText(p3);
    jLabel11.setText(String.valueOf(p5));
    jLabel13.setText(p6);
}

//private javax.swing.JLabel myStatusLabel;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        myStatusLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BOOKING DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 1, 36), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("MOVIE:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("THEATRE:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("FARE:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("SHOW:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("DATE:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("NO OF TICKETS:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(myStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(271, 271, 271))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myStatusLabel)
                .addGap(11, 11, 11))
        );

        jButton1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jButton1.setText("BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jButton2.setText(" CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton1)
                        .addGap(259, 259, 259)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel3)
                .addContainerGap(386, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//this.setVisible(false);         new cardselection(a,b,c,e,N1,f).setVisible(true); 
// تعطيل الأزرار لمنع النقر المتعدد أثناء العملية
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        myStatusLabel.setText("Processing your booking request... please wait."); // عرض رسالة حالة

        logger.info("The ticket booking process has started in the background."); // تسجيل بدء العملية

        // إنشاء وتشغيل SwingWorker
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                // هذا الكود سيعمل في الخلفية (ليس على Event Dispatch Thread)
                // قم هنا بوضع الكود الخاص بحفظ بيانات الحجز في قاعدة البيانات
                // أو أي عملية أخرى تستغرق وقتًا طويلاً.

                // مثال على عملية تستغرق وقتًا (محاكاة):
//                try {
////                    Thread.sleep(3000); // محاكاة عملية تستغرق 3 ثوانٍ
//                    // هنا ستقوم بحفظ البيانات، مثلاً:
//                    // Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/your_db", "user", "pass");
//                    // PreparedStatement ps = conn.prepareStatement("INSERT INTO bookings (movie, theatre, fare, show, tickets, date) VALUES (?, ?, ?, ?, ?, ?)");
//                    // ps.setString(1, a); // وهكذا لبقية المتغيرات
//                    // ps.executeUpdate();
//                    // ps.close();
//                    // conn.close();
//                    logger.info("تم حفظ بيانات الحجز بنجاح."); // تسجيل النجاح
//                } catch (InterruptedException ex) {
//                    logger.severe("عملية الحفظ في الخلفية توقفت بشكل غير متوقع: " + ex.getMessage());
//                    // التعامل مع الاستثناء إذا تم مقاطعة العملية
//                    throw ex; // إعادة طرح الاستثناء ليتم التعامل معه في done()
//                } catch (Exception ex) {
//                    logger.severe("خطأ أثناء حفظ بيانات الحجز: " + ex.getMessage());
//                    // التعامل مع استثناءات قاعدة البيانات أو غيرها
//                    throw ex; // إعادة طرح الاستثناء ليتم التعامل معه في done()
//                }
                return null;
            }
@Override
            protected void done() {
                // هذا الكود سيعمل مرة أخرى على Event Dispatch Thread (EDT)
                // بعد انتهاء مهمة الخلفية (doInBackground).
                try {
//                    get(); // للتحقق مما إذا كان هناك أي استثناءات في doInBackground
                   myStatusLabel.setText("Booking successful!"); // تحديث رسالة الحالة
                    JOptionPane.showMessageDialog(recepit.this, "Booking successful!");

                    // الانتقال إلى الواجهة التالية بعد الانتهاء
                    recepit.this.setVisible(false);
                    new cardselection(a,b,c,e,N1,f).setVisible(true);

                } 
//                catch (InterruptedException ex) {
//                    myStatusLabel.setText("تم إلغاء عملية الحجز.");
//                    JOptionPane.showMessageDialog(recepit.this, "تم إلغاء عملية الحجز.");
//                    logger.warning("المهمة الخلفية تم مقاطعتها: " + ex.getMessage());
//                } 
                catch (Exception ex) {
                    myStatusLabel.setText("Booking failed: " + ex.getMessage());
                    JOptionPane.showMessageDialog(recepit.this, "Booking failed: " + ex.getMessage(), "خطأ", JOptionPane.ERROR_MESSAGE);
                    logger.severe("Failed to complete the background booking task: " + ex.getMessage());
                } finally {
                    // إعادة تمكين الأزرار بغض النظر عن النتيجة
                    jButton1.setEnabled(true);
                    jButton2.setEnabled(true);
                }
            }
        };

        worker.execute(); // بدء مهمة SwingWorker
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//this.setVisible(false);        new CANCEL().setVisible(true);  
// TODO add your handling code here:
                                        
    jButton2.setEnabled(false);
    myStatusLabel.setText("جاري إلغاء الحجز...");

    Connection conn = null;
    PreparedStatement selectStmt = null;
    PreparedStatement deleteStmt = null;
    PreparedStatement updateStmt = null;

    try {
        conn = JavaApplication4.ConnecrDb();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Failed to connect to database. Please try again.");
            System.err.println("Database connection not established. Booking not saved.");
            return;
        }

        conn.setAutoCommit(false); // <- مهم جدًا لتعطيل autocommit!

        // 2. جلب بيانات الحجز
        String selectSql = "SELECT show_id, number_of_tickets_booked FROM bookings WHERE booking_id = ?";
        selectStmt = conn.prepareStatement(selectSql);
        selectStmt.setInt(1, bookingId);

        ResultSet rs = selectStmt.executeQuery();
        if (!rs.next()) {
            throw new SQLException("The requested reservation was not found.");
        }

        int showId = rs.getInt("show_id");
        int ticketsBooked = rs.getInt("number_of_tickets_booked");

        // 3. احذف الحجز من جدول bookings
        String deleteSql = "DELETE FROM bookings WHERE booking_id = ?";
        deleteStmt = conn.prepareStatement(deleteSql);
        deleteStmt.setInt(1, bookingId);
        deleteStmt.executeUpdate();

        // 4. أضف التذاكر مرة أخرى إلى جدول movies_inventory
        String updateSql = "UPDATE movies_inventory SET tickets = tickets + ? WHERE show_id = ?";
        updateStmt = conn.prepareStatement(updateSql);
        updateStmt.setInt(1, ticketsBooked);
        updateStmt.setInt(2, showId);
        updateStmt.executeUpdate();

        // 5. حفظ التغييرات
        conn.commit();

        myStatusLabel.setText("The reservation has been successfully canceled.");
        JOptionPane.showMessageDialog(this, "The booking has been successfully canceled and the tickets have been refunded!");

        this.setVisible(false);
        new CANCEL().setVisible(true);

    } catch (SQLException ex) {
        try {
            if (conn != null && !conn.getAutoCommit()) {
                conn.rollback();
            }
        } catch (SQLException e2) {
            e2.printStackTrace();
        }
        myStatusLabel.setText("Cancellation failed: " + ex.getMessage());
        JOptionPane.showMessageDialog(this, "Failed to cancel the reservation: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } finally {
        try { if (selectStmt != null) selectStmt.close(); } catch (Exception e) {}
        try { if (deleteStmt != null) deleteStmt.close(); } catch (Exception e) {}
        try { if (updateStmt != null) updateStmt.close(); } catch (Exception e) {}
        try { if (conn != null) conn.close(); } catch (Exception e) {}
    }

    jButton2.setEnabled(true);



    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recepit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recepit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recepit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recepit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recepit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel myStatusLabel;
    // End of variables declaration//GEN-END:variables

   
}
